---
 - name: Playbook to install NGINX
   connection: ansible.netcommon.network_cli
   gather_facts: false
   hosts: all
   tasks: 
    - name: Ansible apt install nginx
      apt:
        name: nginx
        state: present


