 - name: Playbook to install NGINX
   hosts: all
   tasks:
    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: Ansible apt install nginx
      apt:
        name: nginx
        state: present
